// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBovrqMQH6dNKNiGucjAkOcenEMRzIHmFA',
    appId: '1:998641628596:web:a6615dff575b58f474aee1',
    messagingSenderId: '998641628596',
    projectId: 'medical-app-f367e',
    authDomain: 'medical-app-f367e.firebaseapp.com',
    storageBucket: 'medical-app-f367e.firebasestorage.app',
    measurementId: 'G-0NXKZ72ZZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtzXXOAUj2oby-eYR2ry0N2_BJilWB9T4',
    appId: '1:998641628596:android:6d120f69d7dbe26774aee1',
    messagingSenderId: '998641628596',
    projectId: 'medical-app-f367e',
    storageBucket: 'medical-app-f367e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABtPPZpYiQI4Q8_Z1COW31dqjZu0cdFe0',
    appId: '1:998641628596:ios:ff5d53e2cf315de374aee1',
    messagingSenderId: '998641628596',
    projectId: 'medical-app-f367e',
    storageBucket: 'medical-app-f367e.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABtPPZpYiQI4Q8_Z1COW31dqjZu0cdFe0',
    appId: '1:998641628596:ios:ff5d53e2cf315de374aee1',
    messagingSenderId: '998641628596',
    projectId: 'medical-app-f367e',
    storageBucket: 'medical-app-f367e.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBovrqMQH6dNKNiGucjAkOcenEMRzIHmFA',
    appId: '1:998641628596:web:3abc96151459dca074aee1',
    messagingSenderId: '998641628596',
    projectId: 'medical-app-f367e',
    authDomain: 'medical-app-f367e.firebaseapp.com',
    storageBucket: 'medical-app-f367e.firebasestorage.app',
    measurementId: 'G-CN7V7M8XL9',
  );
}
